spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
#        type:
#          descriptor:
#            sql: trace

jwt:
  secret-key: asd2103_+dA9sD01casn89423Bh43298-d21evV537
  prefix: "Bearer "
  header: Authorization
  issuer: leejw
  subject: kotiln
  access-token-exp-time: 1
  refresh-token-exp-time: 168