spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
#        type:
#          descriptor:
#            sql: trace

jwt:
  secret-key: asd2103_+dA9sD01casn89423Bh43298-d21evV537
  prefix: "Bearer "
  header: Authorization
  issuer: ljw
  subject: kotiln
  access-token-exp-hours: 1
  refresh-token-exp-hours: 168