spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
#        type:
#          descriptor:
#            sql: trace

jwt:
  secret-key: asd2103_+dA9sD01casn89423Bh43298-d21evV537
  prefix: "Bearer "
  header: Authorization
  issuer: leejw
  subject: kotiln
  access-token-exp-time: 1
  refresh-token-exp-time: 168